### ISSUE TITLE
ScrollView` has no propType for native prop

### ISSUE THREAD

**Issue by alexbigapps23** [GeekyAnts/react-native-boilerplate-mobx-state-tree-flow#1]
ScrollView` has no propType for native prop `RCTScrollView.contentInsetAdjustmentBehavior` of native type `UIScrollViewContentInsetAdjustmentBehavior

Hi, how I can fix it?

**Comment by shivrajkumar** [comment]
@alexbigapps23 The above is version inconsistency issue. Pull the latest changes to fix the version issue
